[project]
name = "modded-nanogpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub[hf-transfer]>=0.35.1",
    "numpy>=2.3.3",
    "torch~=2.8.0",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.3",
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "pre-commit>=4.3.0",
    "seaborn>=0.13.2",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu129", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.ruff]
line-length = 88        # match Black
target-version = "py311"  # or your Python version

[tool.ruff.lint]
# Enable flake8, pyflakes, pycodestyle, isort, and more
select = ["E", "F", "I", "W", "B", "C4"]
# Ignore rules that conflict with Black
ignore = ["E203"]
